kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-claim
spec:
  storageClassName: managed-ha-nfs-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---